apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8-example
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/kindasimple/k8-example.git
    targetRevision: HEAD
    path: deploy/argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true