apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8-example
  namespace: argocd
spec:
  project: prd
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.source.path }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
