apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd
  namespace: argocd
spec:
  description: Development project
  sourceRepos:
    - https://github.com/kindasimple/k8-example.git
  destinations:
    - namespace: prd
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
